/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppVacationsRouteImport } from './routes/_auth/app/vacations'
import { Route as AuthAppTripsRouteImport } from './routes/_auth/app/trips'
import { Route as AuthAppReportsRouteImport } from './routes/_auth/app/reports'
import { Route as AuthAppOrdersRouteImport } from './routes/_auth/app/orders'
import { Route as AuthAppHomeRouteImport } from './routes/_auth/app/home'
import { Route as AuthAppEmployesRouteImport } from './routes/_auth/app/employes'
import { Route as AuthAppContractsRouteImport } from './routes/_auth/app/contracts'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppVacationsRoute = AuthAppVacationsRouteImport.update({
  id: '/vacations',
  path: '/vacations',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppTripsRoute = AuthAppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppReportsRoute = AuthAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppOrdersRoute = AuthAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppHomeRoute = AuthAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppEmployesRoute = AuthAppEmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppContractsRoute = AuthAppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/contracts': typeof AuthAppContractsRoute
  '/app/employes': typeof AuthAppEmployesRoute
  '/app/home': typeof AuthAppHomeRoute
  '/app/orders': typeof AuthAppOrdersRoute
  '/app/reports': typeof AuthAppReportsRoute
  '/app/trips': typeof AuthAppTripsRoute
  '/app/vacations': typeof AuthAppVacationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/contracts': typeof AuthAppContractsRoute
  '/app/employes': typeof AuthAppEmployesRoute
  '/app/home': typeof AuthAppHomeRoute
  '/app/orders': typeof AuthAppOrdersRoute
  '/app/reports': typeof AuthAppReportsRoute
  '/app/trips': typeof AuthAppTripsRoute
  '/app/vacations': typeof AuthAppVacationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/app/contracts': typeof AuthAppContractsRoute
  '/_auth/app/employes': typeof AuthAppEmployesRoute
  '/_auth/app/home': typeof AuthAppHomeRoute
  '/_auth/app/orders': typeof AuthAppOrdersRoute
  '/_auth/app/reports': typeof AuthAppReportsRoute
  '/_auth/app/trips': typeof AuthAppTripsRoute
  '/_auth/app/vacations': typeof AuthAppVacationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/contracts'
    | '/app/employes'
    | '/app/home'
    | '/app/orders'
    | '/app/reports'
    | '/app/trips'
    | '/app/vacations'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/contracts'
    | '/app/employes'
    | '/app/home'
    | '/app/orders'
    | '/app/reports'
    | '/app/trips'
    | '/app/vacations'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/app/contracts'
    | '/_auth/app/employes'
    | '/_auth/app/home'
    | '/_auth/app/orders'
    | '/_auth/app/reports'
    | '/_auth/app/trips'
    | '/_auth/app/vacations'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/vacations': {
      id: '/_auth/app/vacations'
      path: '/vacations'
      fullPath: '/app/vacations'
      preLoaderRoute: typeof AuthAppVacationsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/trips': {
      id: '/_auth/app/trips'
      path: '/trips'
      fullPath: '/app/trips'
      preLoaderRoute: typeof AuthAppTripsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/reports': {
      id: '/_auth/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthAppReportsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/orders': {
      id: '/_auth/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthAppOrdersRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/home': {
      id: '/_auth/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AuthAppHomeRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/employes': {
      id: '/_auth/app/employes'
      path: '/employes'
      fullPath: '/app/employes'
      preLoaderRoute: typeof AuthAppEmployesRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/contracts': {
      id: '/_auth/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AuthAppContractsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppContractsRoute: typeof AuthAppContractsRoute
  AuthAppEmployesRoute: typeof AuthAppEmployesRoute
  AuthAppHomeRoute: typeof AuthAppHomeRoute
  AuthAppOrdersRoute: typeof AuthAppOrdersRoute
  AuthAppReportsRoute: typeof AuthAppReportsRoute
  AuthAppTripsRoute: typeof AuthAppTripsRoute
  AuthAppVacationsRoute: typeof AuthAppVacationsRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppContractsRoute: AuthAppContractsRoute,
  AuthAppEmployesRoute: AuthAppEmployesRoute,
  AuthAppHomeRoute: AuthAppHomeRoute,
  AuthAppOrdersRoute: AuthAppOrdersRoute,
  AuthAppReportsRoute: AuthAppReportsRoute,
  AuthAppTripsRoute: AuthAppTripsRoute,
  AuthAppVacationsRoute: AuthAppVacationsRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
